version: "3.2"
services:
  microapp-seed:
    #build: .
    image: predixapphub/apphub-microapp-seed:latest
    ports:
      - 12345:8080
    environment:
      - "API_DATABASE_ADAPTER=redis"
      - "DEBUG=apphub-microapp-seed:*"
      - "ENABLE_REDIS_STORE=true"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_PASSWORD="
      - "NODE_ENV=production"
      - "RHOST=redis"
    networks:
      - frontend-net
    depends_on:
      - redis
    labels:
      org.label-schema.group: "apphub-microapp"
  
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - frontend-net
    volumes:
      - redis-data:/data
    labels:
      org.label-schema.group: "apphub-microapp"

networks:
  frontend-net:

volumes:
  redis-data: